management:
  endpoints:
    web:
      exposure:
        include: refresh
server:
  port: 9002
  address: 0.0.0.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: items-service
          uri: lb://items
          predicates:
            - Path=/item/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true




eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:9000}/eureka/
  instance:
    preferIpAddress: true
