version: '3.8'
services:
  ms_item_db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}   
      APP_DB_USER: ${APP_DB_USER}   
      APP_DB_PASS: ${APP_DB_PASS}   
      APP_DB_NAME: ${APP_DB_NAME}  
    ports:
      - '5433:5432'
    volumes: 
      - db_item:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d/    
volumes:
  db_item:
    driver: local