spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ms-test-bv/config-server
          clone-on-start: true
          timeout: 100
  application:
    name: test-config
server:
  port: 9001
  address: 0.0.0.0
management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:9000}/eureka/
  instance:
    preferIpAddress: true
